# Generated by Django 4.2.5 on 2023-10-07 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.SmallIntegerField(blank=True)),
                ('projects', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.ImageField(help_text='Upload a background image for the hero section (preferably 1920x1053 size)', upload_to='home/hero', verbose_name='Background image')),
                ('typed_item_1', models.CharField(default='a child of the Most High God', max_length=50)),
                ('typed_item_2', models.CharField(default='highly favored and adored', max_length=50)),
                ('typed_item_3', models.CharField(default='a friend of Jesus', max_length=50)),
                ('typed_item_4', models.CharField(default='... a Christian! 💯', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='home/resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
