# Generated by Django 4.2.5 on 2023-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_projects_fact_repositories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='bg',
        ),
        migrations.AddField(
            model_name='hero',
            name='desktop_bg',
            field=models.ImageField(default='mobile-bg.jpg', help_text='Upload a hero background image for desktop display', upload_to='home/hero', verbose_name='Background image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='mobile_bg',
            field=models.ImageField(blank=True, help_text='Upload a hero background image for mobile display. If not provided, the desktop image will be used instead.', upload_to='home/hero', verbose_name='Background image'),
        ),
    ]
