# Generated by Django 4.2.5 on 2023-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakskevin',
            name='facebook',
            field=models.URLField(blank=True, default='https://www.facebook.com/kevin.wakhisi.50/'),
        ),
    ]
